version: '3.8'
services:
  react-top10:
    restart: always
    hostname: react-top10
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    networks:
      - react-top10
      - express
  mongo:
    restart: always
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: temporary
      MONGO_INITDB_DATABASE: top10lists
    build:
      dockerfile: Dockerfile
      context: ./src/server/mongo
    ports:
      - 3002:3002
      - 27017:27017
    networks:
      - express
      - mongo
  express:
    restart: always
    hostname: express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: temporary
      ME_CONFIG_MONGODB_URL: mongodb://root:temporary@mongo:27017/
    build: 
      dockerfile: Dockerfile
      context: ./src/server
    ports:
      - 3001:3001
    networks:
      - express
      - mongo
  nginx:
    restart: always
    hostname: nginx
    build:
      dockerfile: Dockerfile
      context: ./src/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - react-top10
      - express

networks: 
  react-top10:
  express:
  mongo: